show tail of log while wait for containers to be ready

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -48,8 +48,14 @@ jobs:
         working-directory: dev-env
         run: ./run-env.sh "$E2E_DATAVERSE_IMAGE_TAG"
 
-      - name: Wait for containers to be ready
-        run: timeout 360s sh -c 'while ! docker logs dev_dataverse_bootstrap 2>&1 | grep -q "your instance has been configured"; do sleep 2; done'
+      - - name: Wait for containers to be ready
+          run: |
+            timeout 360s sh -c 'while ! docker logs dev_dataverse_bootstrap 2>&1 | grep -q "your instance has been configured"; do
+              echo "Checking logs..."
+              docker logs dev_dataverse_bootstrap | tail -n 10
+              echo "Text not found, waiting for 2 seconds..."
+              sleep 2
+            done'
 
       - name: Display Docker logs
         run: |
